jobs:
  include:
    - stage: "Unit tests"
      language: python
      python:
        - "3.7"
      notifications:
        email:
          on_success: change
      branches:
        only:
          - master
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest test.client
        - python -m unittest test.schema
        - python -m unittest test.add_thing
        - python -m unittest test.add_thing_batch

    - stage: "Integration test"
      language: python
      python:
        - "3.7"
      notifications:
        email:
          on_success: change
      branches:
        only:
          - master
      env:
        - WEAVIATE_RELEASE_VERSION="0.20.3"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.bash
      script:
        - python ci/integration_test.py

    - stage: "Build documentation"
      notifications:
        email:
          on_success: change
      branches:
        only:
          # Set the documentation only to master and push all the documentation updates to documentation branch
          - master
      script:
        - git checkout documentation
        - make -C documentation html
        - git add documentation
        - git commit -m "Autogenerating documentation 🤖"
        - git push origin documentation
