notifications:
  email:
    on_success: change
language: python
os: linux
# python:
#   - "3.6"
#   - "3.7"
# script: pytest

jobs:
  include:
    - stage: "Unit tests"
      name: "3.6"
      branches:
        only:
          - master
      python: "3.6"
      install:
        - pip install -r requirements.txt
      script:
        - /bin/bash ci/unit_tests/run_unit_tests.bash
    
    - name: "3.7"
      branches:
        only:
          - master
      python: "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - /bin/bash ci/unit_tests/run_unit_tests.bash

    - stage: "Integration test"
      branches:
        only:
          - master
      python: "3.6"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.bash
      script:
        - python ci/integration_test.py

#    - stage: "Build documentation"
#      language: python
#      python:
#        - "3.7"
#      notifications:
#        email:
#          on_success: change
#      branches:
#        only:
#          # Set the documentation only to master and push all the documentation updates to documentation branch
#          - master
#      install:
#        - pip install sphinx
#      script:
#        - /bin/bash ci/generate_doc.bash
