jobs:
  include:
    - stage: "Unit tests"
      language: python
      python:
        - "3.6"
        - "3.7"
      notifications:
        email:
          on_success: change
      branches:
        only:
          - master
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest test.add_thing
        - python -m unittest test.add_thing_batch
        - python -m unittest test.client
        - python -m unittest test.delete
        - python -m unittest test.is_reachable
        - python -m unittest test.patch_thing
        - python -m unittest test.schema


    - stage: "Integration test"
      language: python
      python:
        - "3.6"
        - "3.7"
      notifications:
        email:
          on_success: change
      branches:
        only:
          - master
      env:
        - WEAVIATE_RELEASE_VERSION="0.21.0"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.bash
      script:
        - python ci/integration_test.py

#    - stage: "Build documentation"
#      language: python
#      python:
#        - "3.7"
#      notifications:
#        email:
#          on_success: change
#      branches:
#        only:
#          # Set the documentation only to master and push all the documentation updates to documentation branch
#          - master
#      install:
#        - pip install sphinx
#      script:
#        - /bin/bash ci/generate_doc.bash
