jobs:
  include:
    - stage: "Unit tests"
      language: python
      python:
        - "3.7"
      notifications:
        email:
          on_success: change
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest test.weaviate_instance
        - python -m unittest test.schema
        - python -m unittest test.add_thing
        - python -m unittest test.add_thing_batch

    - stage: "Integration test"
      language: python
      python:
        - "3.7"
      notifications:
        email:
          on_success: change
      env:
        - WEAVIATE_RELEASE_VERSION="0.20.3"
      install:
        - pip install -r requirements.txt
        - pip install .
        - /bin/bash ci/start_weaviate.bash
      script:
        - python ci/integration_test.py