jobs:
  include:
    - stage: "Test"
      name: "Unit tests"
      language: python
      python:
        - "3.7"
      notifications:
        email:
          on_success: change
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest test.weaviate_instance
        - python -m unittest test.schema
